name: Android Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v8

      - name: Set up JDK 17 for Android Gradle
        uses: actions/setup-java@v6
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Get target project git address
        id: get-project
        run: |
          echo "PROJECT=$(cat project-to-build)" >> $GITHUB_ENV

      - name: Clone target android project
        run: git clone --depth=1 ${{ env.PROJECT }} project

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ hashFiles('project/**/*.gradle*', 'project/gradle-wrapper.properties') }}

      - name: Build Android Debug APK
        working-directory: ./project
        run: |
          if [ ! -f "gradlew" ]; then gradle wrapper; fi
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace

      - name: Upload built APK artifact
        uses: actions/upload-artifact@v5
        with:
          name: my-build-apk
          path: project/**/*.apk
